version: '3.8'

services:
  sentiment-dashboard:
    build: .
    ports:
      - "8501:8501"
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    command: streamlit run dashboard.py --server.port=8501 --server.address=0.0.0.0
